### ISSUE TITLE
TS build issue

### ISSUE THREAD

**Issue by kincaidoneil** [testcontainers/testcontainers-node#197]
Since upgrading to 7.x, I run into this error with testcontainers when I try to build my project (with strict mode):

```
../../node_modules/testcontainers/dist/generic-container.d.ts:2:22 - error TS7016: Could not find a declaration file for module 'archiver'. '/home/kincaid/interledgerjs/node_modules/archiver/index.js' implicitly has an 'any' type.
  Try `npm install @types/archiver` if it exists or add a new declaration (.d.ts) file containing `declare module 'archiver';`

2 import archiver from "archiver";
                       ~~~~~~~~~~


Found 1 error.
```

Since `archiver.Archiver` is now part of the [public API on `GenericContainer`](https://github.com/testcontainers/testcontainers-node/blob/747f58356ddd39b36786f1d76731838637e15166/src/generic-container.ts#L95), I think `@types/archiver` needs to be included as a direct dependency, not simply a devDependency.

**Comment by cristianrgreco** [comment]
Thanks for finding+fixing @kincaidoneil, released in [7.6.2](https://github.com/testcontainers/testcontainers-node/releases/tag/v7.6.2)
